resource_group_name = "#{resource_group_name}#"
cos_instance_name = "#{cos_instance_name}#"
cos_bucket_name = "#{cos_bucket_name}#"
cos_bucket_region_location = "#{cos_bucket_region_location}#"
cos_bucket_allowed_ip = "#{cos_bucket_allowed_ip}#"
tags = "#{tags}#"